services:
  oltp-primary:
    image: postgres:15
    command:
      [
        "postgres",
        "-c",
        "config_file=/etc/postgresql/15/postgresql.conf"
      ]
    env_file:
      - oltp-cluster/etc/oltp-primary.env
    networks:
      database-network:
        aliases:
          - oltp-primary
    volumes:
      - type: bind
        source: oltp-cluster/etc/postgresql/15/
        target: /etc/postgresql/15/
        read_only: true
      - type: volume
        source: oltp-primary-volume
        target: /var/lib/postgresql/data
      - type: bind
        source: oltp-cluster/primary/docker-entrypoint-initdb.d/
        target: /docker-entrypoint-initdb.d/
      - type: bind
        source: oltp-cluster/primary/tmp/
        target: /tmp/
    secrets:
      - source: postgres_password
        target: /run/secrets/postgres_password
        uid: "999"
        gid: "999"
        mode: 400
    ports:
      - 5432:5432

secrets:
  postgres_password:
    file: oltp-cluster/.postgres_password
volumes:
  oltp-primary-volume:
networks:
  database-network:
    attachable: true
    name: database-network
