version: "3.9"
services:
    pgadmin:
        image: internal/pgadmin
        env_file:
            - pgadmin/pgadmin.env
        networks:
            db-net:
                aliases:
                    - pgadmin
        ports:
            - target: 80
              published: 8080
              protocol: tcp
              mode: host
        volumes:
            - type: volume
              source: pgadmin-vol
              target: /var/lib/pgadmin
    pgbench-primary:
        image: postgres:15
        env_file:
            - primary-db-cluster/pgbench-primary.env
        networks:
            db-net:
                aliases:
                    - pgbench-primary
        ports:
            - target: 5432
              published: 54321
              protocol: tcp
              mode: host
        volumes:
            - type: volume
              source: pgbench-primary-volume
              target: /var/lib/postgresql/data
            - type: bind
              source: primary-db-cluster/etc/postgresql/15/
              target: /etc/postgresql/15/
              read_only: true
            - type: bind
              source: primary-db-cluster/docker-entrypoint-initdb.d/
              target: /docker-entrypoint-initdb.d/
            - type: bind
              source: primary-db-cluster/tmp/
              target: /tmp/
        command: ["postgres","-c","config_file=/etc/postgresql/15/postgresql.conf"]
    pgbench-replica:
        image: postgres:15
        env_file:
            - replica-db-cluster/pgbench-replica.env
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
                window: 120s
        volumes:
            - type: volume
              source: pgbench-replica-volume
              target: /var/lib/postgresql/data
            - type: bind
              source: replica-db-cluster/etc/postgresql/15
              target: /etc/postgresql/15/
              read_only: true
            - type: bind
              source: replica-db-cluster/docker-entrypoint-initdb.d/
              target: /docker-entrypoint-initdb.d/
        command: ["postgres","-c","config_file=/etc/postgresql/15/postgresql.conf"]
        networks:
            db-net:
                aliases:
                    - pgbench-replica
    grafana:
        image: grafana/grafana:main
        networks:
            db-net:
                aliases:
                    - grafana
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
              mode: host


volumes:
    pgbench-primary-volume:
    pgbench-replica-volume:
        name: 'pgbench-replica-volume_{{.Task.Slot}}'
    pgadmin-vol:
networks:
    db-net:
        driver: overlay
        attachable: true
