version: "3.9"
services:
    db1:
        image: internal/db1
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/db1_postgres_password_file
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data
            PGPORT: 5432
            PGBENCH_PASSWORD_FILE: /run/secrets/db1_pgbench_password_file
            PGBENCH_USER: pgbench
            PGBENCH_DB: pgbench
            PGBENCH_SCALE: 10
        networks:
            db-net:
                aliases:
                    - pgdb1
        ports:
            - target: 5432
              published: 15432
              protocol: tcp
              mode: host
        volumes:
            - type: volume
              source: db1-data-vol-v13
              target: /var/lib/postgresql/data
        secrets:
            - db1_postgres_password_file
            - db1_pgbench_password_file
    db3:
        image: internal/db3
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/db3_postgres_password_file
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data
            PGPORT: 5432
            PGLIB: /var/lib/postgresql/lib/
        networks:
            db-net:
                aliases:
                    - pgdb3
        ports:
            - target: 5432
              published: 35432
              protocol: tcp
              mode: host
        volumes:
            - type: volume
              source: db3-data-vol-v13
              target: /var/lib/postgresql/data
        secrets:
            - db3_postgres_password_file
            - db3_pgbench_password_file

volumes:
    db1-data-vol-v13:
    db3-data-vol-v13:
networks:
    db-net:
        driver: overlay
        attachable: true
secrets:
    db1_postgres_password_file:
        file: ./db1/.postgres_password
    db3_postgres_password_file:
        file: ./db3/.postgres_password
    db1_pgbench_password_file:
        file: ./db1/.pgbench_password
    db3_pgbench_password_file:
        file: ./db3/.pgbench_password
