version: "3.9"
services:
    pgadmin:
        image: internal/pgadmin
        env_file:
            - pgadmin/pgadmin.env
        networks:
            db-net:
                aliases:
                    - pgadmin
        ports:
            - target: 80
              published: 8080
              protocol: tcp
              mode: host
        volumes:
            - type: volume
              source: pgadmin-vol
              target: /var/lib/pgadmin
    pgbench-primary:
        image: internal/primary-db-cluster
        env_file:
            - primary-db-cluster/pgbench-primary.env
        networks:
            db-net:
                aliases:
                    - pgbench-primary-1
        ports:
            - target: 5432
              published: 54321
              protocol: tcp
              mode: host
        volumes:
            - type: volume
              source: pgbench-primary-pg14-volume
              target: /var/lib/postgresql/data
    pgbench-replica:
        image: internal/replica-db-cluster
        env_file:
            - replica-db-cluster/pgbench-replica.env
        depends_on:
            - pgbench-primary
        volumes:
            - type: volume
              source: pgbench-replica-pg14-volume
              target: /var/lib/postgresql/data
        networks:
            db-net:
    pgagent-db1:
        image: internal/pgagent
        environment:
            PGHOST: pgbench-primary-1
        networks:
            db-net:
                aliases:
                  - pgagent-db1
    grafana:
        image: grafana/grafana:main
        networks:
            db-net:
                aliases:
                    - grafana
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
              mode: host


volumes:
    pgbench-primary-pg14-volume:
    pgbench-replica-pg14-volume:
        name: 'pgbench-replica-pg14-volume_{{.Task.Slot}}'
    pgadmin-vol:
networks:
    db-net:
        driver: overlay
        attachable: true
