version: "3.9"
services:
    pgadmin:
        image: internal/pgadmin
        env_file:
            - pgadmin/pgadmin.env
        networks:
            db-net:
                aliases:
                    - pgadmin
        ports:
            - target: 80
              published: 8080
              protocol: tcp
              mode: host
        volumes:
            - type: volume
              source: pgadmin-vol
              target: /var/lib/pgadmin
    db1:
        image: internal/db1
        env_file:
            - db1/db1.env
        networks:
            db-net:
                aliases:
                    - pgdb1
        ports:
            - target: 5432
              published: 54321
              protocol: tcp
              mode: host
        volumes:
            - type: volume
              source: db1-data-vol-v13
              target: /var/lib/postgresql/data
    db2:
        image: internal/db2
        env_file:
            - db2/db2.env
        depends_on:
            - db1
        networks:
            db-net:
                aliases:
                    - pgdb2
        volumes:
            - type: volume
              source: db2-data-vol-v13
              target: /var/lib/postgresql/data
    pgagent-db1:
        image: internal/pgagent
        environment:
            PGHOST: pgdb1
        networks:
            db-net:
                aliases:
                  - pgagent-db1
    grafana:
        image: grafana/grafana:main
        networks:
            db-net:
                aliases:
                    - grafana
        ports:
            - target: 3000
              published: 3000
              protocol: tcp
              mode: host


volumes:
    db1-data-vol-v13:
    db2-data-vol-v13:
    pgadmin-vol:
networks:
    db-net:
        driver: overlay
        attachable: true
