#!/bin/bash -x
#
# Take a base backup of PostgreSQL, store in a backup home using version and cluster names to sort
#

# Import library functions and aliases
source /var/lib/postgresql/lib/bash-functions.bash
source /var/lib/postgresql/lib/postgres-functions.bash
test_libsource || echo "Library import failed! Please check!" 1>&2 # && exit 1

# Postgres-specific environment variables
export PGHOST="pgdb1"
export PGPORT="5432"
export PGDATABASE="postgres"
export PGUSER="postgres"
export PGPASSFILE="/var/lib/postgresql/.pgpass"

# Other applicable globals
export PATH="$PATH" # PATH environment placeholder

# Script-specific global readonly
readonly _pgssupportlist=("14" "13" "12" "11" "10" "9.6")

# Script-specific modifiable globals not modified by execution options
declare _pgsversion
declare _pgscluster
declare -l _xlog_or_wal
declare -l _create_slot

# Script-specific modifiable globals modified by execution options
declare pgsbkupdir="/var/lib/postgresql/backup/base/%version%/%cluster%/" # Specifiy %version% and %cluster% in order to dynamically add version number and cluster name
declare pgswalarchdir="/var/lib/postgresql/backup/wal_archive/%version%/%cluster%/" # Specifiy %version% and %cluster% in order to dynamically add version number and cluster name
declare wal_method="fetch"

function usage()
{
    echo "Usage: pg-basebackup [-D pgsbkupdir] [-W pgswalarchdir] [-x wal_method]
    " 1>&2
    exit 1
}

function check_environment()
{
    _pgsversion="$(get_pgversion)" || return 1
    _pgscluster="$(get_pgclustername)" || return 1

    # Reference for version detection https://why-upgrade.depesz.com/show?from=9.6&to=14&keywords=pg_basebackup
    case ${_pgsversion} in
        "9.6")
            _xlog_or_wal="xlog"
        ;;
        "10"|"11"|"12"|"13"|"14")
            _xlog_or_wal="wal"
        ;;
        "11"|"12"|"13"|"14")
            _create_slot="yes"
        ;;
        *)
            echo "PostgreSQL Version ${_pgsversion} is not supported or is invalid!" 1>&2 && return 1
        ;;
    esac

    return 0
}

function initialize_backupdirs()
{
    local returncode=0
    mkdir -p pgsbkupdir || returncode=$(( ${returncode} + 1 ))
    mkdir -p pgswalarchdir || returncode=$(( ${returncode} + 1 ))
    return ${returncode}
}

# File Main
if [[ "${0}" =~ ^.*pg-basebackup$ ]]; then
    check_environment
    exit 0
fi
